language: python
python:
        "3.6"
env:
        global:
                - MONGODB_VERSION=4.0.3
before_install:
        - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-$MONGODB_VERSION.tgz
        - tar xfz mongodb-linux-x86_64-$MONGODB_VERSION.tgz
        - export PATH=`pwd`/mongodb-linux-x86_64-$MONGODB_VERSION/bin:$PATH
        - mkdir -p data/db
        - mongod --dbpath=data/db &
        - sleep 10
instal:
        - make setup
script:
        - make tests
